const STRINGS = {



	GOOGLE_PALCES_API_KEY: 'AIzaSyClq-KQUvy9b60TbprysJkMgfX-m0y0Ej8',

    FIRST_NAME:'FIRST NAME',
    LAST_NAME:'LAST NAME',
    EMAIL:'EMAIL',
    PASSWORD:'PASSWORD',
    NEXT:'NEXT',
    HOME:'HOME',
    CONTACT_INFORMATION:'CONTACT INFORMATION',
    WHATS_YOUR_NAME:"WHAT'S YOUR NAME AND EMAIL ADDRESS ?",

    CARD_HOLDER_NAME:"CARD HOLDER NAME",
    CARD_NUMBER:"16 DIGITS CARD NUMBER",
    EXPIRY_DATE:"EXPIRY DATE",
    CVV_CODE:"CVV CODE",
    ADDRESS:"ADDRESS",
    CITY:"CITY",

    STATE:"STATE",

    ZIP_CODE:"ZIP CODE",
    COUNTRY:"COUNTRY",
    PHONE_NUMBER:"PHONE NUMBER"
    




}
export default STRINGS;
