// const ACTION_TYPES = {

// 	//user login action keys 
// 	USER_NAME_CHANGED: 'USER_NAME',
// 	PASSWORD_CHANGED: 'PASSWORD_CHANGED',
// 	LOGIN_USER_RES: 'LOGIN_USER_RES',
// 	FETCHING_DATA: 'FETCHING_DATA',
// 	RESET_DATA: 'RESET_DATA',


// 	//PRODUCT_CATEGORY
// 	GET_PRODUCT_CATEGORY_LIST: 'GET_PRODUCT_CATEGORY_LIST',
// 	GET_USER_DETAILS:'GET_USER_DETAILS',
// 	GET_PRODUCT_DETAILS:'GET_PRODUCT_DETAILS',
// 	GET_PRODUCT_LIST:'GET_PRODUCT_LIST',


// 	//user forgot password action keys 
// 	FORGOT_PASS_FETCHING_DATA: 'FORGOT_PASS_FETCHING_DATA',
// 	FORGOT_PASS_RESET_DATA: 'FORGOT_PASS_RESET_DATA',
// 	FORGOT_PASS_RES: 'FORGOT_PASS_RES',
// 	FORGOT_PASS_EMAIL_CHANGED: 'FORGOT_PASS_EMAIL_CHANGED',

// 	//user registration action keys
// 	FIRST_NAME_CHANGED: 'FIRST_NAME_CHANGED',
// 	LAST_NAME_CHANGED: 'LAST_NAME_CHANGED',
// 	EMAIL_CHANGED: 'EMAIL_CHANGED',
// 	PHONE_NUMBER_CHANGED: 'PHONE_NUMBER_CHANGED',
// 	SIGNUP_PASSWORD_CHANGED: 'SIGNUP_PASSWORD_CHANGED',
// 	CONFIRM_PASSWORD_CHANGED: 'CONFIRM_PASSWORD_CHANGED',
// 	SIGNUP_USER_RES: 'SIGNUP_USER_RES',
// 	USER_TYPE: 'USER_TYPE',
// 	SIGNUP_FETCHING_DATA: 'SIGNUP_FETCHING_DATA',

// 	//27 Nov
// 	USER_ROLE_LIST: 'USER_ROLE_LIST',

// 	//Logout action keys
// 	LOGOUT_FETCHING_DATA: 'LOGOUT_FETCHING_DATA',
// 	USER_LOGOUT: 'USER_LOGOUT',
// 	LOGOUT_USER_RES: 'LOGOUT_USER_RES',


// 	//Property screen 
// 	ALL_PROPERTY_LIST: 'ALL_PROPERTY_LIST',
// 	PROPERTY_LIST_FETCHING_DATA: 'PROPERTY_LIST_FETCHING_DATA',

// 	//Home screen 
// 	PROPERTY_LIST: 'PROPERTY_LIST',
// 	HOME_PROPERTY_LIST_FETCHING_DATA: 'HOME_PROPERTY_LIST_FETCHING_DATA',



// 	//Resend password action keys
// 	RESEND_PASS_FETCHING_DATA: 'RESEND_PASS_FETCHING_DATA',
// 	RESEND_PASS_RESET_DATA: 'RESEND_PASS_RESET_DATA',
// 	RESEND_PASS_RES: 'RESEND_PASS_RES',

// 	PHONE_NUMBER_CHANGED: 'PHONE_NUMBER_CHANGED',
// 	ABOUT_USER_CHANGED: 'ABOUT_USER_CHANGED',
// 	CITY_NAME_CHANGED: 'CITY_NAME_CHANGED',
// 	ZIP_CODE_CHANGED: 'ZIP_CODE_CHANGED',



// 	//dashboardScren
// 	PRODUCT_LIST_FETCHING_DATA:'PRODUCT_LIST_FETCHING_DATA',

// }

// export default ACTION_TYPES
